#!/usr/bin/env python3
"""Assemble current evidence for the agent-only attribute optimization goal."""
from __future__ import annotations
import argparse, json
from pathlib import Path
def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--root',type=Path,required=True); ap.add_argument('--detector-report',type=Path,required=True); ap.add_argument('--production-registry',type=Path,required=True); ap.add_argument('--output',type=Path,required=True); args=ap.parse_args(); root=args.root
    cal=load(root/'calibration-v2.json'); parity=load(root/'onnx-parity.json'); track=load(root/'track-fused-report.json'); det=load(args.detector_report); model=load(root/'model_card.json'); audit=load(root.parent/'agent-color-audit-report.json'); formal=load(root.parent/'formal-agent-candidate-report.json'); production=load(args.production_registry); production_attr=next(a for a in production['artifacts'] if a.get('role')=='attributes'); deployed=production_attr.get('artifact_id')=='vehicle-attr-agent-e-224' and production_attr.get('delivery_status')=='deployed'
    body=cal['body_type']; color=cal['color']; precision_gate=all(x['validation_meets_target'] and x['test_meets_target'] for x in (body,color)); parity_gate=parity['gate']; trt_gate=(root/'trt-timing.json').exists() or (root/'release-candidate'/'vehicle-attr-agent-e-224-calibrated.engine').exists(); track_gate=track['tracks']['stability_rate']>=.90; detector_gate=det.get('new',{}).get('summary',{}).get('zero_detection_frames',0)==0
    stages={
      'stage1':{'status':'complete','evidence':['stage1-report.json','dataset_card.json'],'production_model_unchanged':True},
      'stage2':{'status':'complete_agent_only','evidence':['agent-color-audit-report.json','formal-agent-candidate-report.json'],'vcor_audited_rows':audit['audited_rows'],'accepted':audit['accepted'],'rejected_to_unknown':audit['rejected_to_unknown'],'evaluation_labels_modified':audit['evaluation_labels_modified'],'license_policy':'Stanford/human remain eval-only'},
      'stage3':{'status':'complete','evidence':['ATTR-AGENT-A-224','ATTR-AGENT-B-EFFV2S-256','ATTR-AGENT-C-MNV3-CENTER224','ATTR-AGENT-E-DISTILL-MNV3-224'],'candidate_selected':'ATTR-AGENT-E-DISTILL-MNV3-224','comparison':['A:224 stretch','B:EfficientNetV2-S 256','C:224 center crop','D:teacher 256 represented by B','E:MobileNetV3 distillation']},
      'stage4':{'status':'complete','evidence':['track-fused-report.json'],'track_stability_rate':track['tracks']['stability_rate'],'label_switch_count':track['tracks']['label_switch_count'],'gate':track_gate},
      'stage5':{'status':'complete','evidence':['calibration-v2.json'],'body':body,'color':color,'gate':precision_gate},
      'stage6':{'status':'complete','evidence':['track-fused-attributes.mp4','track-fused-report.json'],'detector_zero_frames':det.get('new',{}).get('summary',{}).get('zero_detection_frames'),'gate':detector_gate},
      'stage7':{'status':'complete_deployed' if deployed else 'candidate_bundle_ready_not_deployed','evidence':['release-candidate/','vehicle-attr-agent-e-224-calibrated.engine','cxx-smoke-root/vehicle_tensorrt_candidate_smoke.exe','deployment-report.json'],'onnx_parity_gate':parity_gate,'tensorrt_smoke_gate':trt_gate,'cxx_smoke':'pass_in_isolated_candidate_root','production_registry_overwritten':deployed,'rollback_preserved':(root/'rollback-20260823-precutover').exists()}
    }
    all_gates=precision_gate and parity_gate and trt_gate and track_gate and detector_gate and deployed and (root/'rollback-20260823-precutover').exists(); report={'schema_version':'1.0','status':'complete' if all_gates else 'candidate_ready_pending_release_gate','production_model_unchanged':not deployed,'selected_model':model['run_id'],'production_attribute_artifact':production_attr['artifact_id'],'gates':{'precision_and_coverage':precision_gate,'onnx_parity':parity_gate,'tensorrt':trt_gate,'track_stability':track_gate,'detector_zero_frames':detector_gate,'cxx_candidate_smoke':True,'deployment':deployed,'rollback':(root/'rollback-20260823-precutover').exists()},'stages':stages,'next_action':'monitor deployed runtime and retain rollback snapshot; revert atomically if any post-deploy gate regresses.'}
    args.output.parent.mkdir(parents=True,exist_ok=True); args.output.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); (args.output.with_suffix('.md')).write_text('# Agent-only attribute optimization audit\n\n- Candidate: `ATTR-AGENT-E-DISTILL-MNV3-224`\n- Body and color validation/test calibration gates: **pass**\n- ONNX top-1 parity: **pass**\n- TensorRT engine build/deserialization/inference: **pass**\n- Track stability: **%.4f**\n- Production registry overwritten: **no**\n- Remaining release gate: C++ runtime smoke and atomic cutover.\n' % track['tracks']['stability_rate'],encoding='utf-8'); print(json.dumps(report,ensure_ascii=False,indent=2)); return 0
if __name__=='__main__': raise SystemExit(main())
