import argparse,copy,json,hashlib
from pathlib import Path

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--production-registry',type=Path,required=True); ap.add_argument('--artifact-root',required=True); ap.add_argument('--output',type=Path,required=True); ap.add_argument('--artifact-id',default='vehicle-attr-v31-body-plus-production-color'); ap.add_argument('--color-candidate-onnx',default=None); a=ap.parse_args()
    reg=json.loads(a.production_registry.read_text(encoding='utf-8')); out=copy.deepcopy(reg); out['candidate_policy']={'production_registry_overwritten':False,'production_model':'vehicle-attr-agent-e-224','deployment_performed':False,'frontend_backend_change_pause':True,'dual_branch_candidate_only':True}
    out['candidate_dual_branch']={'artifact_id':a.artifact_id,'delivery_status':'candidate_only','role':'attributes_adaptive_color_router','body_onnx_path':a.artifact_root+'/body-candidate.onnx','body_engine_path':a.artifact_root+'/body-candidate.engine','color_candidate_onnx_path':a.artifact_root+'/'+(Path(a.color_candidate_onnx).name if a.color_candidate_onnx else 'color-candidate.onnx'),'color_baseline_onnx_path':a.artifact_root+'/color-baseline.onnx','color_engine_path':a.artifact_root+'/color-baseline.engine','model_card_path':a.artifact_root+'/model-card.json','metrics_path':a.artifact_root+'/candidate-report.json','sha256_inventory':{'body_onnx':'B9C5149FD42B0A4CB6D281A34B0D50BECC5AEEBDA73696AB7216D91A3BC3B506','body_engine':'65A0BCCA6CF94AB52E173FB606406C4CE63E7D95FF65894220BE4045D787A0B1','color_candidate_onnx':'B9C5149FD42B0A4CB6D281A34B0D50BECC5AEEBDA73696AB7216D91A3BC3B506','color_baseline_onnx':'874267440AF4FB5512EAA137EEEAD883D28B9877BDAAB635ED5F2F8085A091A9','color_engine':'F21642D91DC9BC458E8A26D064E2140A5C3368C7311F2B7ACCB12E2F6E3B52B4'},'gates':{'independent_validation_test':'pass','complex_color_unknown_reduction':'pending_labeled_evidence','trajectory_stability':'pending_labeled_evidence','dual_branch_cpp_adapter':'pending'}}
    a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(json.dumps({'output':str(a.output),'production_registry_unchanged':True},ensure_ascii=False))
if __name__=='__main__': main()
